services:
  - type: web
    name: waste-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir /opt/render/project/src app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9 # Use your specific Python version
